postgresql:
  enabled: false

concourse:
  imageDigest: sha256:cb0ad2abda87bfb695a68e3d6377fad369be5f77d208bb83f2b57261fb8e88e2
  postgresql:
    enabled: false
  worker:
    replicas: 3
    resources:
      requests:
        cpu: 1500m
        memory: 3072Mi
      limits:
        cpu: 6000m
        memory: 3072Mi
  web:
    replicas: 2
    service:
      type: LoadBalancer
      loadBalancerIP: 35.202.14.65
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
  concourse:
    web:
      auth:
        mainTeam:
          localUser: admin
          github:
            team: concourse:Pivotal
        github:
          enabled: true
      bindPort: 80
      enableGlobalResources: true
      encryption: { enabled: true }
      externalUrl: https://hush-house.concourse-ci.org
      kubernetes: { keepNamespaces: true }
      logLevel: debug
      metrics: { captureErrorMetrics: true }
      prometheus: { enabled: true }
      postgres:
        host: 10.99.0.3
        database: atc
      tls: { enabled: true, bindPort: 443 }
    worker:
      rebalanceInterval: 5m
      baggageclaim: { driver: overlay }
