{{- if .Values.grafana.enabled -}}
{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "metrics.fullname" . }}-datasource-prometheus
  labels:
    app: {{ template "metrics.name" . }}
    chart: {{ template "metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: grafana
    {{ grafana.sidecar.datasources.label }}: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://{{ template "prometheus.fullname" . }}
      password:
      user:
      database:
      basicAuth:
      basicAuthUser:
      basicAuthPassword:
      withCredentials:
      isDefault: true
      editable: true
{{- end -}}
{{- end -}}
