{{- if .Values.grafana.enabled }}
{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metrics.fullname" . }}-tls
  labels:
    app: {{ template "metrics.name" . }}
    chart: {{ template "metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  cert: {{ required "tls.cert must be provided" .Values.tls.cert | b64enc | quote }}
  key: {{ required "tls.key must be provided" .Values.tls.key | b64enc | quote }}
{{- end }}
{{- end }}
