{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metrics.fullname" . }}-tls
  labels:
    app: {{ template "metrics.name" . }}
    chart: {{ template "metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  cert: {{ .Values.tlsCert | b64enc | quote }}
  key: {{ .Values.tlsKey | b64enc | quote }}
{{- end }}
