vault:
  global:
    tlsDisable: false
  server:
    nodeSelector: 'cloud.google.com/gke-nodepool: generic-1'
    extraVolumes:
      - type: secret
        name: vault-server-tls
    standalone:
      enabled: true
      config: |
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
          tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
          tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.ca"
        }

        storage "file" {
          path = "/vault/data"
        }
