---
platform: linux

inputs:
- { name: hush-house }
- { name: helm-values, optional: true }

params:
  DEPLOYMENT:
  DEPLOYMENT_TYPE:

run:
  path: /bin/bash
  args:
  - -ce
  - |
    apk add --update make curl


    # kubectl credential setup
    mkdir -p ~/.kube
    echo '((kube-config-b64))' | base64 -d >~/.kube/config


    # helm setup
    helm init --client-only
    echo '((helm-ca-cert-b64))' | base64 -d > $(helm home)/ca.pem
    echo '((helm-cert-b64))' | base64 -d > $(helm home)/cert.pem
    echo '((helm-key-b64))' | base64 -d > $(helm home)/key.pem

    helm repo remove local
    helm repo add concourse https://raw.githubusercontent.com/concourse/charts/gh-pages
    helm plugin install https://github.com/databus23/helm-diff --version master


    # conditionally set deployment credentials
    if [[ -d ./helm-values ]]; then
      cat ./helm-values/.values.yaml > ./hush-house/deployments/$DEPLOYMENT_TYPE/$DEPLOYMENT/.values.yaml
    fi


    # get into the deployment-type specific directory
    cd ./hush-house/deployments/$DEPLOYMENT_TYPE


    # conditionally perform the deployment if there are any diffs
    make diff-$DEPLOYMENT && \
      echo "No changes!" || \
      { [[ $? == "2" ]] && echo "y" | make deploy-$DEPLOYMENT; }

