# Default values for shuttle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

concourse:
  worker:
    replicas: 2
    tolerations:
    - key: preemptible
      operator: Exists
    resources:
      requests:
        cpu: 3000m
        memory: 3072Mi
      limits:
        cpu: 6000m
        memory: 3072Mi
  web:
    replicas: 2
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
  postgresql:
    metrics:
      enabled: true
    persistence:
      storageClass: ssd
    resources:
      requests:
        cpu: 250m
        memory: 768Mi
      limits:
        cpu: 250m
        memory: 768Mi
  concourse:
    web:
      logLevel: debug
      bindPort: 80
      kubernetes:
        keepNamespaces: false
      prometheus:
        enabled: true
      auth:
        mainTeam:
          github:
            team: concourse:Pivotal
        github:
          enabled: true
    worker:
      rebalanceInterval: 10m
      baggageclaim:
        logLevel: debug
        driver: overlay

prometheus:
  enabled: true
  nodeExporter:
    enabled: true
    tolerations:
    - key: preemptible
      operator: Exists
  kubeStateMetrics:
    enabled: true
  pushgateway:
    enabled: false
  alertmanager:
    enabled: false
  server:
    persistentVolume:
      enabled: true
      size: 30Gi
      storageClass: ssd

grafana:
  enabled: true
  service:
    type: LoadBalancer
  sidecar:
    datasources:
      enabled: true
      label: grafana/datasource
    dashboards:
      enabled: true
      label: grafana/dashboard
