# Default values for shuttle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

concourse:
  worker:
    replicas: 3
    resources:
      requests:
        cpu: 1000m
        memory: 2048Mi
      limits:
        cpu: 1000m
        memory: 2048Mi
  web:
    replicas: 2
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
  postgresql:
    metrics:
      enabled: true
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 256Mi
        cpu: 250m
  concourse:
    web:
      logLevel: debug
      bindPort: 80
      kubernetes:
        keepNamespaces: false
      prometheus:
        enabled: true
      auth:
        mainTeam:
          github:
            team: concourse:Pivotal
        github:
          enabled: true
    worker:
      baggageclaim:
        logLevel: debug
        driver: naive

prometheus:
  enabled: true
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: false
  pushgateway:
    enabled: false
  alertmanager:
    enabled: false
  server:
    persistentVolume:
      enabled: true

grafana:
  enabled: true
  service:
    type: LoadBalancer
  sidecar:
    datasources:
      enabled: true
      label: grafana/datasource
    dashboards:
      enabled: true
      label: grafana/dashboard
