apiVersion: v1
kind: Secret
metadata:
  name: vault-server-tls
type: Opaque
data:
  {{- if not .Values.vault.global.tlsDisable  }}
  vault.ca: {{ default "" .Values.vault.ca  | b64enc | quote }}
  vault.crt: {{ default "" .Values.vault.crt | b64enc | quote }}
  vault.key: {{ default "" .Values.vault.key | b64enc | quote }}
  {{- end }}
