image:
  repository: cirocosta/slirunner
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9001
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9001"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: { cloud.google.com/gke-nodepool: generic-1 }
tolerations: []
affinity: {}

slirunner:
  concourseUrl: https://hush-house.pivotal.io
  interval:
  prefix:

secrets:
  username:
  password:
