---
dependencies:
- name: prometheus
  version: 9.3.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: prometheus.enabled

- name: grafana
  version: 4.0.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: grafana.enabled
