apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slirunner.fullname" . }}
  labels:
{{ include "slirunner.labels" . | indent 4 }}
type: Opaque
data:
  username: {{ required "local user username must be supplied" .Values.secrets.username | b64enc | quote }}
  password: {{ required "local user password must be supplied" .Values.secrets.password  | b64enc | quote}}
