---
dependencies:
- name: prometheus
  version: 8.4.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: prometheus.enabled

- name: grafana
  version: 1.22.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: grafana.enabled
