apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "sysctl.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sysctl.name" . }}
    helm.sh/chart: {{ include "sysctl.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sysctl.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sysctl.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          terminationGracePeriodSeconds: '5'
          command:
            - /bin/sh
            - -c
            - |
              set -o errexit
              set -o xtrace

              {{- if empty .Values.sysctl }}
                {{ fail "at least one sysctl option must be set." }}
              {{- end }}

              while sysctl -w {{ range .Values.sysctl }}{{ . }}{{- end }}
              do
                sleep 120s
              done
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
