concourse:
  image: concourse/concourse-rc
  imageTag: latest
  persistence: { enabled: false }
  worker:
    replicas: 1
  concourse:
    web:
      enableGlobalResources: true
      ephemeral: true
      kubernetes: { enabled: false }
      prometheus: { enabled: true }
