postgresql:
  enabled: false

concourse:
  image: concourse/concourse
  imageTag: 5.0.0

  postgresql:
    enabled: false

  persistence:
    worker:
      storageClass: ssd
      size: 350Gi

  worker:
    replicas: 4
    livenessProbe:
      periodSeconds: 20
      timeoutSeconds: 10
    nodeSelector: { cloud.google.com/gke-nodepool: workers-1 }
    hardAntiAffinity: true
    env:
      - name: CONCOURSE_GARDEN_NETWORK_POOL
        value: "10.254.0.0/16"
      - name: CONCOURSE_GARDEN_MAX_CONTAINERS
        value: "2000"
    resources:
      requests:
        cpu: 5000m
        memory: 20Gi
      limits:
        cpu: 7000m
        memory: 20Gi

  web:
    replicas: 2
    nodeSelector: { cloud.google.com/gke-nodepool: generic-1 }
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: hush-house-web
                release: hush-house
    service:
      type: LoadBalancer
      loadBalancerIP: 35.202.14.65
    resources:
      requests:
        cpu: 750m
        memory: 1Gi
      limits:
        cpu: 750m
        memory: 1Gi

  concourse:
    web:
      auth:
        mainTeam:
          localUser: admin
          github:
            team: concourse:Pivotal
        github:
          enabled: true
      bindPort: 80
      containerPlacementStrategy: fewest-build-containers
      enableGlobalResources: true
      encryption: { enabled: true }
      externalUrl: https://hush-house.concourse-ci.org
      kubernetes: { keepNamespaces: true }
      logLevel: debug
      metrics: { captureErrorMetrics: true }
      prometheus: { enabled: true }
      postgres:
        host: 10.99.0.3
        database: atc
      tls: { enabled: true, bindPort: 443 }
    worker:
      ephemeral: false
      rebalanceInterval: 30m
      baggageclaim: { driver: overlay }
      healthcheckTimeout: 10s
