postgresql:
  enabled: false

concourse:
  postgresql:
    enabled: false

  persistence:
    worker:
      storageClass: ssd
      size: 500Gi

  worker:
    annotations:
      rollingUpdate: "1"
    replicas: 4
    terminationGracePeriodSeconds: 3600
    livenessProbe:
      periodSeconds: 60
      timeoutSeconds: 30
    nodeSelector: { cloud.google.com/gke-nodepool: workers-1 }
    hardAntiAffinity: true
    env:
    - name: CONCOURSE_GARDEN_NETWORK_POOL
      value: "10.254.0.0/16"
    - name: CONCOURSE_GARDEN_MAX_CONTAINERS
      value: "2000"
    resources:
      limits:
        cpu: 15000m
        memory: 29Gi

  web:
    annotations:
      rollingUpdate: "1"
    replicas: 2
    nodeSelector: { cloud.google.com/gke-nodepool: generic-1 }
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: hush-house-web
                release: hush-house
    service:
      type: LoadBalancer
      loadBalancerIP: 35.202.234.135
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 1Gi

  concourse:
    web:
      auth:
        mainTeam:
          localUser: admin
          github:
            team: concourse:Pivotal
        github:
          enabled: true
      bindPort: 80
      containerPlacementStrategy: random
      enableGlobalResources: true
      encryption: { enabled: true }
      externalUrl: https://hush-house.pivotal.io
      kubernetes: { keepNamespaces: true }
      metrics: { captureErrorMetrics: true }
      prometheus: { enabled: true }
      postgres:
        host: 173.255.117.168
        database: atc
        sslmode: verify-ca
      tls: { enabled: true, bindPort: 443 }
    worker:
      ephemeral: false
      rebalanceInterval: 1h
      baggageclaim: { driver: detect }
      healthcheckTimeout: 25s
