postgresql:
  enabled: false

concourse:
  image: concourse/concourse
  imageDigest: sha256:e138c16a77c54ed7530594169485f9bee3d097a3caf0aa32718bc1efc8e769e2

  postgresql:
    enabled: false

  worker:
    enabled: false

  web:
    annotations:
      rollingUpdate: "1"
    replicas: 2
    nodeSelector: { cloud.google.com/gke-nodepool: generic-1 }
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: hush-house-web
                release: hush-house
    service:
      type: LoadBalancer
      loadBalancerIP: 35.202.234.135
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi

  concourse:
    web:
      auth:
        mainTeam:
          localUser: admin
          github:
            team: concourse:Pivotal
        github:
          enabled: true
      bindPort: 80
      clusterName: hush-house
      containerPlacementStrategy: random
      defaultDaysToRetainBuildLogs: 30
      enableBuildAuditing: true
      enableContainerAuditing: true
      enableGlobalResources: true
      enableJobAuditing: true
      enablePipelineAuditing: true
      enableResourceAuditing: true
      enableSystemAuditing: true
      enableTeamAuditing: true
      enableVolumeAuditing: true
      enableWorkerAuditing: true
      encryption: { enabled: true }
      externalUrl: https://hush-house.pivotal.io
      kubernetes: { keepNamespaces: true }
      metrics: { captureErrorMetrics: true }
      prometheus: { enabled: true }
      tls: { enabled: true, bindPort: 443 }
      postgres:
        host: 173.255.117.168
        database: atc
        sslmode: verify-ca
