postgresql:
  enabled: false

concourse:
  image: concourse/concourse-rc
  imageDigest: sha256:a22eb7ce823413d6e580fbb2fd4c65488f8c16ab62a871f346adf0b49c06b520

  secrets:
    teamAuthorizedKeys:
    - team: diego
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCf8Dd5PmIbfM7WodkOeE8gkbWv6J9dOofMXcGW6MI6JwvCBZne/LxmyFNZYpr0VniFUjUxB/juT/Qmp0r3WhMDh/s4hcAE+AtkE4FPFUUgoNiAd+Lo69dc1rK/1bAafn8dgOse45t/vn7+cA0f89ygbxAtPOIPMjFVU2S32R7ocuUCRrniT558XvLso0bETqJhzLTM8TjYgl61SyjZR/Ew8rG2LM4sBI9a4dA7LLdHv7AW+5ci/a4VW7sIV4tdhzszGbA3SrRvnm/RMGpZCVd8+2uHd78rNmackQhd+Hgln4e9c8ZsVV1hBcwkEbHtLE/iW6uuILR62dVmmWXfY6Mt'

  postgresql:
    enabled: false

  worker:
    enabled: false

  web:
    annotations:
      rollingUpdate: "1"
    replicas: 2
    nodeSelector: { cloud.google.com/gke-nodepool: generic-1 }
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: hush-house-web
                release: hush-house
    service:
      type: LoadBalancer
      loadBalancerIP: 35.202.234.135
    resources:
      requests:
        cpu: 1500m
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 1Gi

  concourse:
    web:
      auth:
        mainTeam:
          localUser: admin
          github:
            team: concourse:Pivotal
        github:
          enabled: true
      bindPort: 80
      clusterName: hush-house
      containerPlacementStrategy: random
      defaultDaysToRetainBuildLogs: 30
      enableLidar: true
      enableBuildAuditing: true
      enableContainerAuditing: true
      enableGlobalResources: true
      enableJobAuditing: true
      enablePipelineAuditing: true
      enableResourceAuditing: true
      enableSystemAuditing: true
      enableTeamAuditing: true
      enableVolumeAuditing: true
      enableWorkerAuditing: true
      encryption: { enabled: true }
      externalUrl: https://hush-house.pivotal.io
      kubernetes: { keepNamespaces: true }
      metrics: { captureErrorMetrics: true }
      prometheus: { enabled: true }
      tls: { enabled: true, bindPort: 443 }
      postgres:
        host: 173.255.117.168
        database: atc
        sslmode: verify-ca
