apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "concourse.concourse.fullname" . }}-tls
  labels:
    app: {{ template "concourse.concourse.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  tls.crt: {{ .Values.tlsCert | b64enc | quote }}
  tls.key: {{ .Values.tlsKey | b64enc | quote }}
