{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "shuttle.fullname" . }}-tls
  labels:
    app: {{ template "shuttle.name" . }}
    chart: {{ template "shuttle.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    foo: bar
type: Opaque
data:
  cert: {{ .Values.grafana.tls.cert | b64enc | quote }}
  key: {{ .Values.grafana.tls.key | b64enc | quote }}
{{- end }}
