resources:
- name: hush-house
  type: git
  source:
    uri: https://((github-token))@github.com/cirocosta/hush-house

- name: maintenance-image
  type: registry-image
  source:
    repository: cirocosta/charts-maintenance

- name: charts-repository
  type: git
  source:
    uri: https://((github-token))@github.com/concourse/charts
    branch: gh-pages


jobs:
- name: deploy
  serial: true
  plan:
  - aggregate:
    - get: maintenance-image
    - get: charts-repository
      trigger: true
    - get: hush-house
      trigger: true
    - task: helm-values
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: busybox }
        outputs:
        - name: helm-values
        run:
          path: /bin/sh
          args:
          - -cex
          - "echo '((hush-house-values-b64))' | base64 -d > ./helm-values/.values.yaml"
  - task: run
    image: maintenance-image
    params: { DEPLOYMENT: hush-house }
    file: hush-house/ci/deploy.yml
